### ISSUE TITLE
"image number greater than total number of images" error

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/buda-iiif-presentation#12]
http://library.bdrc.io/show/bdr:W1PD96684_0206 cannot retrieve manifest because `workLocation` page numbers seem inconsistent: http://presentation.bdrc.io/2.1.1/v:bdr:V1PD96684_I1PD106659::534-552/manifest

![image](https://user-images.githubusercontent.com/33383857/46465473-f6a20500-c7c8-11e8-9ec8-dd9290aac93f.png)

in same Work but another Volume it is fine: http://library.bdrc.io/show/bdr:W1PD96684_0608

**Comment by eroux** [comment]
Well, I'm affraid  iiif-presentation is right here, it's a bug in the data: http://library.bdrc.io/show/bdr:V1PD96684_I1PD106659 says it has 512 pages, and W1PD96684_0206 claims a text goes from page 534 to 552. So either the location is wrong (so it's a bug in rKTs-migration), or we don't have all the images for this volume (in which case, not much we can do)

**Comment by berger-n** [comment]
looking deeper in http://library.bdrc.io/show/bdr:W1PD96684_S0001 
* first it seems that many Volumes are missing in http://library.bdrc.io/show/bdr:I1PD96684
(manifest ok but error 500 in first image, eg http://iiifpres.bdrc.io/2.1.1/v:bdr:V1PD96684_I1PD106654/manifest VS http://iiif.bdrc.io/image/v2/bdr:V1PD96684_I1PD106654::I1PD1066530001.tif/full/full/0/default.jpg )
* n°[129](http://library.bdrc.io/show/bdr:W1PD96684_0129) says `Vol.6 p.598|4 - p.609|8` but n°[130](http://library.bdrc.io/show/bdr:W1PD96684_0139) says `Vol.6 p.4|1 - p.315|3` ...  then n°[137](http://library.bdrc.io/show/bdr:W1PD96684_0137) ("otani catalogue reference") says `Vol.6 p.531|5 - p.574|6` but n°[138](http://library.bdrc.io/show/bdr:W1PD96684_0138) says `Vol.6 p.4|1 - p.6|2`... does not seem clear to me how to read that ?

**Comment by eroux** [comment]
the data about locations is created in rKTs-migration so if there's an actual bug in the data (comparing the page numbers provided by rKTs-migration and the Otani catalog), it should be reported there. The problem seems to come from a possible misinterpretation of the [rKTs data](https://github.com/brunogml/rKTs/blob/master/Kanjur/peking.xml#L1296) on my side. But that's a different topic from the images that don't work.

The images that don't work are a problem that should be reported on buda-iiif-server.

**Comment by eroux** [comment]
For this issue, I think there should just be a warning and the manifest should be generated (and trucated anyway)

**Comment by eroux** [comment]
done for the warning, the rest is  an issue with the data
