### ISSUE TITLE
inconsistency between manifest and actual image list

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/buda-iiif-presentation#7]
manifest uses wrong first image index in http://library.bdrc.io/show/bdr:W22083 :
- actual first image is 38040001.tif / http://purl.bdrc.io/query/IIIFPres_volumeInfo?R_RES=bdr%3AV22083_I3804 / http://iiif.bdrc.io/image/v2/bdr:V22083_I3804::38040001.tif/full/full/0/default.jpg
- whereas manifest gives 37540010.tif / http://iiif.bdrc.io/image/v2/bdr:V22083_I3804::37540010.tif/full/full/0/default.jpg which is not found on S3 server : `Works/fe/W22083/images/W22083-3804/37540010.tif
The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;`

**Comment by eroux** [comment]
This is a problem in the S3 data, @TBRC-JimK : 

s3://archive.tbrc.org/Works/fe/W22083/images/W22083-3708/dimensions.json

lists files such as `"filename": "38140001.tif"`, etc. that correspond to another image group... can you fix that? I'll close the issue as it's not related to iiif-presentation

**Comment by TBRC-JimK** [comment]
All set. I don't know why it happened, but I refreshed from the existing builds.
